### ISSUE TITLE
Konu Bulut/2.Bulut 

### ISSUE THREAD

**Issue by 40345839668** [MicrosoftDocs/azure-docs.tr-tr#43]
Windows yada linuks veya androit fark etmez onedryve google drayve 2 veya daha fazla bulut hizmetlerini kullanıyorsanız yalnızca tek bir browzer yada tarayıcı kullanmalısınız aksi halde güvenlik yada windows defender sorunu ile karşılaşmanız kaçınılmaz.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: ecae7814-3a8b-1401-34b7-a3f53d22b9e5
* Version Independent ID: 30254acc-2901-0565-e7dc-619c279f8b78
* Content: [Azure Danışmanı giriş](https://docs.microsoft.com/tr-tr/azure/advisor/advisor-overview)
* Content Source: [articles/advisor/advisor-overview.md](https://github.com/MicrosoftDocs/azure-docs.tr-tr/blob/live/articles/advisor/advisor-overview.md)
* Service: **advisor**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by gosali** [comment]
Merhaba @40345839668 
,
--
Katkılarınıza çok değer veriyoruz. Ekibimiz, yalnızca belgelerle ilgili geri bildirimlere yanıt verebilir.
Ürün geri bildiriminizi lütfen DOCS sayfasının sonundaki “Ürün Geri Bildirimi Yap” düğmesini kullanarak gönderin.
Belgelerle ilgili bir geri bildiriminiz varsa, lütfen bunu bu kanal yoluyla göndermekten çekinmeyin.
Makalelerimize yaptığınız katkılar bizim için çok değerlidir.

Saygılarımla,
Microsoft DOCS Uluslararası Ekibi

**Comment by 40345839668** [comment]
Yalnız bulut,un farkı tabiki İnkâr edilemez.
