### ISSUE TITLE
Django Binding Problem

### ISSUE THREAD

**Issue by erdemlal** [MicrosoftDocs/azure-docs.tr-tr#46]
I tried to run a django app, in the document above it says 

For Django apps, App Service looks for a file named wsgi.py within your app code, and then runs Gunicorn using the following command:
gunicorn --bind=0.0.0.0 --timeout 600 &lt;module&gt;.wsgi

But actually it logs the following:
2018-12-24T10:12:44.228591212Z GUNICORN_CMD_ARGS="--bind=0.0.0.0 --timeout 600" gunicorn config.wsgi
2018-12-24T10:12:45.819439562Z [2018-12-24 10:12:45 +0000] [35] [INFO] Starting gunicorn 19.6.0
2018-12-24T10:12:45.820397596Z [2018-12-24 10:12:45 +0000] [35] [INFO] Listening at: http://127.0.0.1:8000 (35)

So the command doesn't bind 0.0.0.0, it binds 127.0.0.1 which causes to not reaching application, but when i used a custom startup command like:
gunicorn --bind=0.0.0.0 --timeout 600 config.wsgi

I can reach the application, so i think there is a problem related with GUNICORN_CMD_ARGS environment variable, you should consider to change default Django command without using GUNICORN_CMD_ARGS

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 4348313e-7280-dc7e-4943-14c4675bbe5a
* Version Independent ID: 970e6640-8042-5f88-5ecf-84d58d09b8fd
* Content: [Linux üzerinde - Azure App Service'e Python uygulamaları yapılandırma](https://docs.microsoft.com/tr-tr/azure/app-service/containers/how-to-configure-python#django-app)
* Content Source: [articles/app-service/containers/how-to-configure-python.md](https://github.com/MicrosoftDocs/azure-docs.tr-tr/blob/live/articles/app-service/containers/how-to-configure-python.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **astay;cephalin;kraigb**

**Comment by CeciAc** [comment]
Hello, @erdemlal 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/21665.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by JennyLawrance** [comment]
We launch all our flask/django apps with the default startup script, and have verified that it works with GUNICORN_CMD_ARGS:
That said, not using that environment variable is also an option we can consider. We will test this out and share an ETA.

**Comment by JennyLawrance** [comment]
@erdemlal Do you have the sitename where you faced this issue? (Send me an email (jennylaw(at)microsoft(dot)com
