### ISSUE TITLE
edu mailim olduğu halde hata almaktayım

### ISSUE THREAD

**Issue by FReeWaLLe** [MicrosoftDocs/azure-docs.tr-tr#47]
edu mailim olduğu halde hata almaktayım Geçerli hesap türünüz desteklenmiyor hatası almaktayım

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 107576e7-75ca-e4f7-34df-04f4992f1e21
* Version Independent ID: 64fbc1cd-065b-a4a6-7324-60ee8ca6f9ff
* Content: [Azure kaynak sağlayıcısı kayıt hataları](https://docs.microsoft.com/tr-tr/azure/azure-resource-manager/resource-manager-register-provider-errors)
* Content Source: [articles/azure-resource-manager/resource-manager-register-provider-errors.md](https://github.com/MicrosoftDocs/azure-docs.tr-tr/blob/live/articles/azure-resource-manager/resource-manager-register-provider-errors.md)
* Service: **azure-resource-manager**
* GitHub Login: @tfitzmac
* Microsoft Alias: **tomfitz**

**Comment by LisandroSu** [comment]
Merhaba @FReeWaLLe 
Katkılarınıza çok değer veriyoruz. Ekibimiz, yalnızca belgelerle ilgili geri bildirimlere yanıt verebilir. 
Ürün geri bildiriminizi lütfen DOCS sayfasının sonundaki “Ürün Geri Bildirimi Yap” düğmesini kullanarak gönderin. 
Belgelerle ilgili bir geri bildiriminiz varsa, lütfen bunu bu kanal yoluyla göndermekten çekinmeyin. 
Makalelerimize yaptığınız katkılar bizim için çok değerlidir.  
Saygılarımla, 
Microsoft DOCS Uluslararası Ekibi
