### ISSUE TITLE
AADSTS90002 error 

### ISSUE THREAD

**Issue by Ayshine** [MicrosoftDocs/azure-docs.tr-tr#523]
Hello,

I am following the tutorial below. 

https://docs.microsoft.com/tr-tr/azure/iot-accelerators/iot-accelerators-connecting-pi-c

But I am getting 
`AADSTS90002: Tenant '94f6bd32-f368-41a5-af7c-4843bab05151' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.` 
error. when I click Time Series Insight. I give permission  to the user and the app user. Still getting the same error. (View device telemetry -> 1st step)
---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 552fcbfd-a025-6a6d-74a3-470f606ee4ad
* Version Independent ID: fac901c8-abcf-7a05-629f-0c4e1cfad979
* Content: [Raspberry Pi C - Azure'ı kullanarak Uzaktan izleme sağlama](https://docs.microsoft.com/tr-tr/azure/iot-accelerators/iot-accelerators-connecting-pi-c#feedback)
* Content Source: [articles/iot-accelerators/iot-accelerators-connecting-pi-c.md](https://github.com/MicrosoftDocs/azure-docs.tr-tr/blob/master/articles/iot-accelerators/iot-accelerators-connecting-pi-c.md)
* Service: **iot-accelerators**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by srvbpigh** [comment]
Hello, @Ayshine
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Ayshine, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48685. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
