### ISSUE TITLE
Çeviri hatası / Mistranslation

### ISSUE THREAD

**Issue by leventguner** [MicrosoftDocs/azure-docs.tr-tr#524]
"Unsupervised learning", denetimli öğrenme olarak çevrilmiş. Denetimsiz öğrenme olması gerekiyor.
Unsupervised learning was translated as "denetimli öğrenme" to Turkish. It should be "denetimsiz öğrenme".
---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 5cfad9fe-242d-c81a-319a-393ace5480a5
* Version Independent ID: fad36df8-e42c-3246-3fde-388f4bc670ba
* Content: [Machine Learning algoritması bir sayfa - Azure Machine Learning](https://docs.microsoft.com/tr-tr/azure/machine-learning/algorithm-cheat-sheet#feedback)
* Content Source: [articles/machine-learning/algorithm-cheat-sheet.md](https://github.com/MicrosoftDocs/azure-docs.tr-tr/blob/master/articles/machine-learning/algorithm-cheat-sheet.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @FrancescaLazzeri
* Microsoft Alias: **lazzeri**

**Comment by srvbpigh** [comment]
Hello, @leventguner
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Merhaba @leventguner,

Geri bildiriminiz için teşekkür ederiz. Söz konusu sayfada makine çevirisi yapılmıştır, bu nedenle içerik tam olarak anlaşılır olmayabilir. Yakın zamanda sağ tarafa “İngilizce Dilinde Oku” seçeneği ekledik, bu seçeneği kullanarak dil ayarlarını değiştirmeden İngilizce sürüme geçebilirsiniz.

Saygılarımla,
Microsoft DOCS Uluslararası Ekibi
